//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mastermind.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mastermind.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborting....
        /// </summary>
        internal static string GameStateLabel_Aborting {
            get {
                return ResourceManager.GetString("GameStateLabel_Aborting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game In Progress.
        /// </summary>
        internal static string GameStateLabel_InProgress {
            get {
                return ResourceManager.GetString("GameStateLabel_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Lost!.
        /// </summary>
        internal static string GameStateLabel_Lost {
            get {
                return ResourceManager.GetString("GameStateLabel_Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Won!.
        /// </summary>
        internal static string GameStateLabel_Won {
            get {
                return ResourceManager.GetString("GameStateLabel_Won", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No TryParse method defined for type..
        /// </summary>
        internal static string GeneticSettingsForm_NoParseMethod {
            get {
                return ResourceManager.GetString("GeneticSettingsForm_NoParseMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum pool size exceeded..
        /// </summary>
        internal static string KnuthSolver_OutOfMemory {
            get {
                return ResourceManager.GetString("KnuthSolver_OutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No settings for this solver..
        /// </summary>
        internal static string RandomSolver_NoSettings {
            get {
                return ResourceManager.GetString("RandomSolver_NoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop tests before closing this window..
        /// </summary>
        internal static string TestForm_StopTests {
            get {
                return ResourceManager.GetString("TestForm_StopTests", resourceCulture);
            }
        }
    }
}
